[[redirects]]
  from = "/proxy/*"
  to = "https://api.openweathermap.org/:splat"
  status = 200
  force = true

[build]
  environment = { REACT_APP_WEATHER_API_KEY = "a4157db9eb299058145cdf841898ff26" }

[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  REACT_APP_TOML_ENV_VAR = "From netlify.toml (REACT_APP_)"